version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "nlpsandbox/maintainers"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    ignore:
      - dependency-name: python
        versions: ["3.9.x"]
    reviewers:
      - "nlpsandbox/maintainers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "nlpsandbox/maintainers"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "nlpsandbox/maintainers"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "nlpsandbox/maintainers"