version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/db"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "tschaffter"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "tschaffter"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "tschaffter"