version: "3.8"

services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: data-node-db
    restart: always
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "${SQL_PORT}:5432"

  api:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: data-node-api
    environment:
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_DB
      - SQL_PORT
      - SYNAPSE_USERNAME
      - SYNAPSE_API_KEY
      - DATA_SYNAPSE_ID
      - DATA_MD5
      - GOLDSTANDARD_SYNAPSE_ID
      - GOLDSTANDARD_MD5
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - database

volumes:
    database-data:

