version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_PG
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "6000:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - SYNAPSE_USERNAME
      - SYNAPSE_APIKEY
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
    database-data:

