version: "3.8"

services:
  db:
    image: postgres:12.4
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  api:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SYNAPSE_USERNAME: ${SYNAPSE_USERNAME}
      SYNAPSE_APIKEY: '${SYNAPSE_APIKEY}'