name: ci

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*.*.*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfiles
      uses: docker://hadolint/hadolint:latest
      with:
        entrypoint: hadolint
        args: server/Dockerfile
    - name: Check that packages in requirements.txt files are in asc order
      run: |
        sort -f --check server/requirements.txt
        sort -f --check server/test-requirements.txt

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        cp .env.sample .env
        export $(grep -v '^#' .env | xargs -d '\n')
    - name: Validate docker-compose.yml
      run: docker-compose -f docker-compose.yml config >/dev/null

